searchTerm=https://parabank.parasoft.com/parabank/index.htm
invalidEmail=test@abc.com
invalidPassword=password
expectedTitleHomepage=ParaBank | Welcome | Online Banking
expectedTitleLogin=ParaBank | Welcome | Online Banking
validEmail=valid@abc.com
validPassword=password